version: 2.1

jobs:
  pytest:
    docker:
      - image: cimg/python:3.8.13
    resource_class: large
    steps:
      - run:
          name: Inspect Python
          command: |
            which python
            python --version
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run: |
          pytest

workflows:
  main:
    jobs:
      - pytest
