version: 2.1

jobs:
  pytest:
    docker:
      - image: cimg/python:3.8.13
    parallelism: 3
    resource_class: large
    steps:
      - run:
          name: Inspect Python
          command: |
            which python
            python --version
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Inspect test cases
          command: |
            pytest --collect-only -q
      - run:
          name: Run tests (specific ones only)
          command: |
            pytest --collect-only -q | grep '::' > tests.txt

            cat tests.txt | circleci tests split --split-by=timings --timings-type=testname > split.txt

            # verify
            wc -l split.txt

            mkdir test-reports
            cat split.txt | xargs pytest --junitxml=test-reports/test.xml
      - store_test_results:
          path: ./test-reports/
      - store_artifacts: # upload test coverage as artifact
          path: ./test-reports/test.xml

workflows:
  main:
    jobs:
      - pytest
